image: maven:3.6.1-jdk-8

services:
  - name: selenium/standalone-chrome
    alias: selenium


stages:
  - prepare
  - test

prepare:
  stage: prepare
  script:
    - mvn clean compile

test:
  variables:
    SELENIUM_HOST: selenium
  stage: test
  script:
    - mvn test
